services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shortops
    ports:
      - "5432:5432"
    volumes:
      - shortops_pg:/var/lib/postgresql/data

volumes:
  shortops_pg:
